// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using theFootyDataWorkerService.Models;

#nullable disable

namespace theFootyDataWorkerService.Migrations
{
    [DbContext(typeof(footyDbContext))]
    partial class footyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("theFootyDataWorkerService.Models.MatchEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("awayTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullTimeResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("halfTimeResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homeTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("matchId")
                        .HasColumnType("int");

                    b.Property<int?>("matchday")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("utcDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("winner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
